version: '3.9'

services:

  nginx:
    build: ./nginx/build
    restart: always
    ports:
      - 80:80
      - 443:443

  frontend:
    build: ./frontend
    container_name: "frontend"
    restart: "always"

  backend:
    build: ./backend
    container_name: "backend"
    restart: "always"

