version: '3.9'

services:
  #  traefik:
  #    image: "traefik:v2.9"
  #    container_name: "traefik"
  #    command:
  #      #- "--log.level=DEBUG"
  #      - "--api.insecure=true"
  #      - "--providers.docker=true"
  #      - "--providers.docker.exposedbydefault=false"
  #      - "--entrypoints.web.address=:80"
  #    ports:
  #      - "80:80"
  ##      - "8080:8080"
  #    volumes:
  #      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  nginx:
    build: ./nginx/build
    restart: always
    ports:
      - 80:80
      - 443:443

  frontend:
    build: ./frontend
    container_name: "frontend"
    restart: "always"
      #    labels:
      #      - "traefik.enable=true"
      #      - "traefik.http.routers.frontend.rule=Host(`invest-hackathon.ru`)"
      #      - "traefik.http.routers.frontend.entrypoints=web"
      #      - "traefik.http.routers.frontend.tls=true"
      #      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      #
#    ports:
#      - 127.0.0.1:80:8080

  backend:
    build: ./backend
    container_name: "backend"
    restart: "always"
      #    ports:
      #    labels:
      #- "traefik.enable=true"
      #- "traefik.http.routers.backend.rule=(Host(`invest-hackathon.ru`) && PathPrefix(`/api`))"
      #- "traefik.http.routers.backend.entrypoints=web"

      #  database:
      #    image: postgres

